<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBW1rF1s\testsImanaging_ApiCommunicationBundle_Tests_ApiCommunicationTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBW1rF1s/testsImanaging_ApiCommunicationBundle_Tests_ApiCommunicationTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBW1rF1s.legacy');

    return;
}

if (!\class_exists(testsImanaging_ApiCommunicationBundle_Tests_ApiCommunicationTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBW1rF1s\testsImanaging_ApiCommunicationBundle_Tests_ApiCommunicationTestingKernelTestDebugContainer::class, testsImanaging_ApiCommunicationBundle_Tests_ApiCommunicationTestingKernelTestDebugContainer::class, false);
}

return new \ContainerBW1rF1s\testsImanaging_ApiCommunicationBundle_Tests_ApiCommunicationTestingKernelTestDebugContainer([
    'container.build_hash' => 'BW1rF1s',
    'container.build_id' => '52c40235',
    'container.build_time' => 1552474499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBW1rF1s');
